### ISSUE TITLE
Groups/Ranks

### ISSUE THREAD

**Issue by Hetal728** [PlasmaShaft/PlasmaShaft#1]
Groups/Ranks will have to be eventually, but how will they be saved? In the PlayerInfo/PlayerDB or in separate files. How will the configuration be saved (What format will it be in)? Will the ranks be hierarchical or will it be like fCraft's command grouping system? If it is indeed like fCraft's command system, then what disadvantages would users face?

**Comment by LeChosenOne** [comment]
I'm not a fan of the whole hierarchy thing. It's so linear. The fCraft grouping system would be more complex, but also a thousand times for flexible. We'll have to have some kind of config.xml to save the customizations from the config tool, so we can save ranks in their since that's where we'll be making the ranks anyway. Things that will have to be stored: rank name, color, and commands allowed. The only disadvantage to the fCraft grouping system would be that it would take the host a little bit more time to set up since there is a bit more to do. Other than that, it seems to be the better option.

**Comment by Hetal728** [comment]
I've seen that a disadvantage of the fCraft system is that you can't allow single commands, you need to allow the whole command group. An example would be that /Test and /Debug are hooked to DevCmds, but I only want a certain rank to use /Test, not /Debug, since the command groups are hard-coded, it'll take some C# skills to change it.

**Comment by LeChosenOne** [comment]
Well, that's if you copy and paste the fCraft ranks directly lol. We could do a permission system like fCraft, or we could do individual commands, not too different.

**Comment by Hetal728** [comment]
So do you want to do them? You seem to have this well planned.
